---
fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-ast
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
-    repo: https://github.com/astral-sh/ruff-pre-commit
     rev: v0.11.7 # Ruff version.
     hooks: # Run the linter.
     -   id: ruff
         types_or: [ python, pyi ]
         args: [ --fix ]
     -   id: ruff-format # Run the formatter.
         types_or: [ python, pyi ]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: python-use-type-annotations
-   repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
    -   id: yamllint
        args: ["-d", "{ignore: .pre-commit-config.yaml}"]
        language: python
        types: [yaml]
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle
        language: python
        types: [python]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        language: python
        types: [python]
        additional_dependencies: [black==20.8b1]
